pub mod bigfile;
pub mod class;
pub mod crc32;
pub mod crc64;
pub mod dynarray;
pub mod error;
pub mod keyframer;
pub mod link_header;
pub mod lz;
pub mod macros;
pub mod map;
pub mod math;
pub mod names;
pub mod option;
pub mod platforms;
pub mod strings;
pub mod traits;
pub mod versions;

pub type BffError = crate::error::Error;
pub type BffResult<T> = std::result::Result<T, BffError>;
pub type Endian = binrw::Endian;
pub type BufReader<T> = binrw::io::BufReader<T>;
