name: Build wasm

on: [push, pull_request]

permissions: {}

jobs:
  build:
    name: Build for wasm
    runs-on: ubuntu-latest
    concurrency:
      group: build-wasm-${{ github.ref }}-build
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Configure Rust toolchain
        run: |
          rustup toolchain install 1.85.0 --profile minimal --no-self-update
          rustup default 1.85.0
          rustup target add wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6

      - name: Download wasi-sdk
        uses: suisei-cn/actions-download-file@818d6b7dc8fe73f2f924b6241f2b1134ca1377d9
        with:
          url: "https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-20/wasi-sdk-20.0-linux.tar.gz"

      - name: Install dependencies
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/wasi-sdk/"
          tar -xzvf wasi-sdk-20.0-linux.tar.gz --strip-components=1 -C "${GITHUB_WORKSPACE}/wasi-sdk/"
          cargo install --locked trunk

      - name: Build
        run: trunk build --release --locked
        env:
          CC: "${GITHUB_WORKSPACE}/wasi-sdk/bin/clang --sysroot=${GITHUB_WORKSPACE}/wasi-sdk/share/wasi-sysroot"
        working-directory: ./bff-gui/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          path: ./bff-gui/dist/

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !github.event.repository.fork
    runs-on: ubuntu-latest
    concurrency:
      group: build-wasm-${{ github.ref }}-deploy
      cancel-in-progress: true

    permissions:
      pages: write # Required to publish the built site to GitHub Pages.
      id-token: write # Required to authenticate to GitHub Pages via OIDC.

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
